<div id="view-dashboard" class="p-6 space-y-8">
    <div>
        <div class="flex flex-wrap gap-2 mb-4" id="stats-filter-container">
            <button class="stats-filter-btn" data-period="today">Today</button><button class="stats-filter-btn" data-period="7days">7 Days</button><button class="stats-filter-btn" data-period="30days">30 Days</button><button class="stats-filter-btn" data-period="6months">6 Months</button><button class="stats-filter-btn active" data-period="all">All Time</button>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4" id="stats-display-container"></div>
    </div>
    <div>
        <h2 class="text-xl font-bold text-gray-700 mb-4">Manage Coupons</h2>
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
            <div class="bg-gray-50 p-6 rounded-lg border">
                <h3 class="text-lg font-semibold mb-4">Add New Coupon</h3>
                <form action="api.php" method="POST" class="space-y-4"><input type="hidden" name="action" value="add_coupon"><div><label class="block mb-1.5 text-sm font-medium text-gray-700">Coupon Code</label><input type="text" name="code" class="form-input uppercase" placeholder="e.g., SALE20" required></div><div><label class="block mb-1.5 text-sm font-medium text-gray-700">Discount (%)</label><input type="number" name="discount_percentage" class="form-input" placeholder="e.g., 20" required min="1" max="100"></div><div><label class="block mb-1.5 text-sm font-medium text-gray-700">Coupon Scope</label><select name="scope" id="coupon_scope" class="form-select"><option value="all_products">All Products</option><option value="category">Specific Category</option><option value="single_product">Single Product</option></select></div><div id="scope_category_container" class="hidden"><label class="block mb-1.5 text-sm font-medium text-gray-700">Select Category</label><select name="scope_value_category" class="form-select"><?php foreach($all_products_data as $cat): ?><option value="<?= htmlspecialchars($cat['name']) ?>"><?= htmlspecialchars($cat['name']) ?></option><?php endforeach; ?></select></div><div id="scope_product_container" class="hidden"><label class="block mb-1.5 text-sm font-medium text-gray-700">Select Product</label><select name="scope_value_product" class="form-select"><?php foreach($all_products_for_js as $prod): ?><option value="<?= htmlspecialchars($prod['id']) ?>"><?= htmlspecialchars($prod['name']) ?></option><?php endforeach; ?></select></div><div class="flex items-center gap-2 pt-2"><input type="checkbox" name="is_active" id="is_active" value="true" checked class="h-4 w-4 rounded border-gray-300 text-[var(--primary-color)] focus:ring-[var(--primary-color)]"><label for="is_active" class="text-sm font-medium text-gray-700">Activate Coupon</label></div><div><button type="submit" class="btn btn-primary"><i class="fa-solid fa-circle-plus"></i>Add Coupon</button></div></form>
            </div>
            <div class="bg-gray-50 p-6 rounded-lg border">
                <h3 class="text-lg font-semibold mb-4">Existing Coupons</h3>
                <div class="space-y-3 max-h-[25rem] overflow-y-auto pr-2"><?php if (empty($all_coupons_data)): ?><p class="text-gray-500 text-center py-4">No coupons found.</p><?php else: ?><?php foreach ($all_coupons_data as $coupon): ?><div class="flex items-center justify-between p-3 bg-white rounded-lg border flex-wrap"><div><p class="font-bold text-base uppercase"><?= htmlspecialchars($coupon['code']) ?> <span class="ml-2 text-sm font-normal text-gray-500"><?= htmlspecialchars($coupon['discount_percentage']) ?>% Off</span></p><?php $scope_display_value = $coupon['scope_value'] ?? ''; if (($coupon['scope'] ?? 'all_products') === 'single_product' && !empty($scope_display_value)) { foreach ($all_products_for_js as $p) { if ($p['id'] == $scope_display_value) { $scope_display_value = $p['name']; break; } } } ?><p class="text-xs text-blue-600 font-semibold mt-1">Scope: <?= htmlspecialchars(ucwords(str_replace('_', ' ', $coupon['scope'] ?? 'all_products'))) ?><?php if(!empty($coupon['scope_value'])): ?> (<?= htmlspecialchars($scope_display_value) ?>)<?php endif; ?></p></div><div class="flex items-center gap-3"><span class="text-sm font-bold py-0.5 px-2 rounded-full <?= $coupon['is_active'] ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' ?>"><?= $coupon['is_active'] ? 'Active' : 'Inactive' ?></span><form action="api.php" method="POST" onsubmit="return confirm('Are you sure?');"><input type="hidden" name="action" value="delete_coupon"><input type="hidden" name="coupon_id" value="<?= $coupon['id'] ?>"><button type="submit" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash-can"></i></button></form></div></div><?php endforeach; ?><?php endif; ?></div>
            </div>
        </div>
    </div>
</div>